import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meal Planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
          <path
            fill="#0099ff"
            d="M0,64L34.3,90.7C68.6,117,137,171,206,176C274.3,181,343,139,411,112C480,85,549,75,617,80C685.7,85,754,107,823,144C891.4,181,960,235,1029,224C1097.1,213,1166,139,1234,101.3C1302.9,64,1371,64,1406,64L1440,64L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"
          ></path>
        </svg>
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to a new way to plan meals</h1>
        <p className={styles.description}>
          Born of the daily struggle to come up with what to eat and what to buy
          at the grocery store
        </p>
        <div className={styles.grid}>
          <Link href="/all-recipes">
            <a className={styles.card}>
              <h2>Get started &rarr;</h2>
              <p>
                Discover the art of letting randomization dictate what you feed
                yourself for a week
              </p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://www.kristencoy.com" rel="noopener noreferrer">
          Created with heavy usage of documentation
        </a>
      </footer>
    </div>
  );
}
